wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.27
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.5
    t:
      1:
      - 1
      - 5
      2:
      - 1
      - 5
      4: 3.8.5
      5: 0.10.27
      8:
      - 5
attention_dim:
  desc: null
  value: 256
batch_size:
  desc: null
  value: 128
decoder_dim:
  desc: null
  value: 256
embedding:
  desc: null
  value: '300'
embedding_dim:
  desc: null
  value: 300
epochs:
  desc: null
  value: 2
learning_rate:
  desc: null
  value: 0.001
model:
  desc: null
  value: resnet101_attention
